[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "github-repo-analyzer"
version = "0.1.0"
description = "A CLI tool that analyzes GitHub repositories and generates user stories using Claude Code SDK"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
keywords = ["github", "claude", "ai", "user-stories", "cli"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "claude-code-sdk>=0.0.20",
    "click>=8.0.0",
    "requests>=2.31.0",
    "rich>=13.0.0",
    "anyio>=4.0.0",
    "pathlib2>=2.3.7; python_version < '3.4'",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
]

[project.scripts]
github-repo-analyzer = "github_repo_analyzer.cli:main"

[project.urls]
Homepage = "https://github.com/yourusername/github-repo-analyzer"
Repository = "https://github.com/yourusername/github-repo-analyzer"
Issues = "https://github.com/yourusername/github-repo-analyzer/issues"

[tool.black]
line-length = 88
target-version = ['py310']

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
